First pull request
andresporras3423/enumerable-module-ruby pull request #2
Opened 2020-02-27 21:22 UTC by abcussi

- test the methods with 4 examples for each method.
- the methods pass all the tests.
- using procs' in the injects test.
- using symbols in the inject test.
- testing methods with Booleans', numbers and strings.

2020-02-28 06:59 UTC, suretrust requested changes
Hi team, 👋 

### Great job implementing the tests! 🙌 Please see my comments on your code. 👇 

**Kindly submit another code review request once this has been fixed.** _Happy coding!_ 🎉

2020-02-28 06:59 UTC, suretrust commented on spec/enum_spec.rb
> +    enum = Enum.new
Use `let` here instead. You can check [this article](https://github.com/rubocop-hq/rspec-style-guide#let-blocks) to understand why.

2020-02-28 06:59 UTC, suretrust commented on spec/enum_spec.rb
> +      expect(enum.test_1_my_each).to eql(2)
* [ ] Ensure to test for negative scenarios. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))
#### Example
```ruby
expect(enum.test_1_my_each).to eql(2)
expect(enum.test_1_my_each).not_to eql(4)
```

2020-02-28 06:59 UTC, suretrust commented on spec/enum_spec.rb
> +    it 'testing method my_each_with_index' do
`[Best practice][Optional]:` When writing your `it` block, it should be followed by a singular verb.
#### Example:
```ruby
it 'returns the sum of odd values' do
   expect(enum.test_1_my_each_with_index).to eql(8)
   expect(enum.test_1_my_each_with_index).not_to eql(13)
end

it 'returns the sum of even values' do
   expect(enum.test_2_my_each_with_index).to eql(11)
   expect(enum.test_2_my_each_with_index).not_to eql(16)
end
```

2020-02-28 06:59 UTC, suretrust commented on spec/enum_spec.rb
> +  end
`[Optional]`: You could move the `Enum` class to a new file and import it into this file using `require_relative.` This makes your code more modular.

2020-02-28 20:44 UTC, andresporras3423 commented
* Using let for enum instance
* testing negative scenarios with not_to eql
*  Using singular verb for it blocks
* enum class is in another file

2020-02-29 18:09 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @abcussi and @andresporras3423 :handshake: 

### Thank you for doing the changes requested by the previous reviewer, :medal_sports: your project looks better now still as a follow up of the changes you've made I've requested some changes in your code bellow, please address them :point_down: 

### that's it, team! :raised_hands: 

### Please :pray:  do the changes :man_technologist: :man_technologist: and submit back for a code review when you are done

Happy coding! :rocket: 

Any question? tell me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-02-29 18:09 UTC, euqueme commented on spec/enum_spec.rb
> +      expect(enum.test_4_my_each_with_index).to eql('hello world')
- [ ] You should have one `it` block for each expected behavior [for example:](https://github.com/rubocop-hq/rspec-style-guide#let-blocks)

- [ ] Also be more descriptive with every behaviour :point_down: 
```
.
.
describe "my_each_with_index" do
  it "handles a variable within a block and display its result" do
    expect(enum.test_2_my_each_with_index).to eql(11)
  end 
  it "handles a logic variable within a block and it doesn't display a wrongful result" do
   expect(enum.test_3_my_each_with_index).not_to eql(false)
  end 
.
.
.
end
```
please do this for all your test cases not just this one :v:

2020-02-29 18:09 UTC, euqueme commented on spec/enum_spec.rb
> +  describe '#add' do
- [ ] Enclose all test cases from each enumerable method  in their own `describe` block [for example](https://github.com/rubocop-hq/rspec-style-guide#empty-lines-around-examples):

```
Rspec.describe Enum do
let(:enum) { Enum.new }
describe 'my_each' do
  it 'test case # 1' do
  end
  it 'test case # 2' do
  end
end
.
.
.
describe 'my_map' do
  it 'test case # 1' do
  end
  it 'test case # 2' do
  end
end
```

do this for all your enum methods :v:

2020-02-29 19:09 UTC, andresporras3423 commented
Hi Maria Eugina, 

Thank you for your feedback, I will make the changes required.

2020-02-29 21:00 UTC, andresporras3423 commented
* Using one 'it' for each test
* One describe for each method
* More descriptive with the purpose of each test

2020-03-01 06:32 UTC, whiz25 approved these changes
## Congz :clap: 
Your code looks good and all test cases pass. It's a :+1: from me. Merge and proceed.

### Martin Afani

2020-03-01 12:44 UTC, andresporras3423 commented
Thank you Afani

2020-03-01 12:44 UTC, merged